### ISSUE TITLE
Left-hand flipping

### ISSUE THREAD

**Issue by fortserious** [dmitrio95/fretboard-plugin#4]
Hi, this is a very useful plugin, thanks!

I was wondering if it would be possible to make an option for flipping the fretboard horizontally, for left-handed players. Currently I have to flip it mentally when I'm going back and forth between my bass and the software and this would save me a lot of time.

I'd fork it myself, but my theory knowledge is still pretty rudimentary and I'm not sure which functions or arrays I'd need to modify.

Cheers!

**Comment by dmitrio95** [comment]
Hi, thanks for the kind words!

This is indeed a good request, didn't think of that myself. I have added a change to allow flipping, please check if this works for you. It seems to do the right thing but I might have missed something in my tests. Just replace the `Fretboard.qml` file with [the new version](https://raw.githubusercontent.com/dmitrio95/fretboard-plugin/master/Fretboard.qml) of it to check it out.

Thanks!

**Comment by fortserious** [comment]
Wow, thank you for such a quick response! I've just tested and it seems to be working perfectly - this is exactly what I needed. I really appreciate you taking the time!
